# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_announcement_badge'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='badges',
            field=models.ManyToManyField(to='main.Badge'),
        ),
    ]
